### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by TheIllusiveC4** [TheIllusiveC4/CorpseComplex#1]
There's a bug that causes some items to be duplicated upon respawning. This occurs very rarely, and seems to disregard whether it is kept or dropped. This is a bug that has appeared since very early iterations of the code so I hoped it would have disappeared after several major rewrites but it is still possible as of version 0.5b. I cannot currently decipher what code is causing this and I cannot reliably duplicate it (I only see it once every few dozen deaths at most, even duplicating the exact situation immediately following the bug's occurrence does not duplicate it), so I am at a bit of a standstill. 

I'm opening this issue myself to gather any information from players who may have encountered this bug as well, until a time where I am certain the bug has been fixed.

**Comment by TheIllusiveC4** [comment]
After testing version 0.6b, it appears the duplication happens even without the activation of the death event listeners. As it's difficult to reproduce, I can't be certain yet, but this is highly suggestive that this is not a bug with the mod itself.

**Comment by psymin** [comment]
On a server that I'm currently testing, items are being duplicated upon death every time I have the inventory module on.  Disabling the inventory module seems to disable the duplication, that is about as far as I've gotten on troubleshooting.

**Comment by TheIllusiveC4** [comment]
Can you replicate this with only Corpse Complex? I'd like to at least rule out other mods interfering with the death logic.

Also, if you're using this with other mods, can you provide the modlist?
