### ISSUE TITLE
The Camping Mod slots

### ISSUE THREAD

**Issue by DEX47** [TheIllusiveC4/CorpseComplex#10]
Noted an issue with mod incompatibility with The Camping Mod. Item in the always kept list will be kept unless they are in The Camping Mod specific item slots. Would love to see some compatibility included.

```
# List of items that are always kept
S:"Essential Items" <
camping:bag
camping:knife
camping:lantern
```

**Comment by TheIllusiveC4** [comment]
I've never used the Camping Mod, but I'll see what I can do.
