### ISSUE TITLE
Sync (Suggestion)

### ISSUE THREAD

**Issue by CannibalKon** [TheIllusiveC4/CorpseComplex#11]
I'm unsure if there IS compatibility between this mod and Sync, but I would love the idea of being able to modify what happens when the player runs out of shells, aka a keepinventory ability that only works if there are shells left! If there is any cross compatibility between this mod and that one, this will definitely stay a must have on my list.

**Comment by TheIllusiveC4** [comment]
This'll depend on how Sync is coded, but I'll definitely look into it!

**Comment by TheIllusiveC4** [comment]
So it's been a while, but I did look into this. 

Unfortunately, it looks like this sort of support would be very difficult, if not explicitly impossible, to do. It doesn't seem like Sync was really coded with this kind of inventory transfer in mind, as there's no way I can see to pull out the origin shell's inventory during the syncing progress.
