### ISSUE TITLE
[Suggestion] Increase max Power for effects

### ISSUE THREAD

**Issue by MasterEnderman** [TheIllusiveC4/CorpseComplex#12]
Hello I'm making a modpack and want to give the player resistence 5 so he is invulnerable for a short period of time. At the moment this isn't possible, because as statet in your wiki the highest powerlevel is 4.
Is there a chance that you could increase it?

**Comment by TheIllusiveC4** [comment]
Sure, why not? I honestly have no idea why I set the max to 4 in the first place.

**Comment by TheIllusiveC4** [comment]
Still awaiting Curse approval, but the newest update raises the maximum power to 10.
