### ISSUE TITLE
Suggestion: Finer grained control for random drop in Inventory module

### ISSUE THREAD

**Issue by darloth** [TheIllusiveC4/CorpseComplex#13]
Ideally I'd like to be able to configure it so that equipment is not dropped, but is damaged, and then a partial random amount of any stackable items are dropped.

Currently this seems impossible as if random drop percentage is turned on, it applies to everything.

As a probably easier middle ground, it would be nice if I could apply the random drop chance only to the main inventory and guarantee keeping hotbar, mainhand, offhand, armour.

**Comment by TheIllusiveC4** [comment]
I'm willing to implement this, but it might take a bit of time. Something like this would need some rewrites about how the inventory code runs, so I'll see what I can do first.
