### ISSUE TITLE
[Suggestion] Ability to execute command(s) on player death

### ISSUE THREAD

**Issue by imIrony** [TheIllusiveC4/CorpseComplex#14]
Self explanatory suggestion to be able to run any command upon player death, perhaps being able to make it dimension dependent as well.

**Comment by TheIllusiveC4** [comment]
Could you give an example? I understand the basic concept of course, I'd just like to grasp what kind of specific use-case you're interested in.

**Comment by imIrony** [comment]
I was planning on using it in combination with Reskillable which is a mod that adds various skills to the game, it also adds a command “/reskillable resetall” that resets all the players skills, so I wanted to be able to reset all player skills on death.

**Comment by TheIllusiveC4** [comment]
So there were some issues with adding command usage, particularly regarding the fact that permission checks would block many attempts.

Instead, I've considered your use-case and added in support for Reskillable directly by adding in a config option to reset all skills on respawn.

**Comment by imIrony** [comment]
Well for the modpack I am working on uses [ThutsPerms](https://minecraft.curseforge.com/projects/thutperms) to make sure command permissions aren't a problem but I can see why issues would rise from that kind of implementation, thank you for the case-specific feature!
