### ISSUE TITLE
[Bug] Reset player skills on death setting original skill values after incrementing one skill point after death

### ISSUE THREAD

**Issue by imIrony** [TheIllusiveC4/CorpseComplex#15]
A bug that involves the new configuration option that resets player skills on death for the Reskillable mod, after incrementing any single skill by one point all skills are automatically reset to the skill levels prior to the player death.

Using latest version of Corpse Complex 1.0.5 and Reskillable 1.12.5.

**Comment by TheIllusiveC4** [comment]
Hm, that's weird. I can only assume this is some sort of syncing issue. I'll look into it.
