### ISSUE TITLE
SoulBound enchantment missing

### ISSUE THREAD

**Issue by UnixParadigm** [TheIllusiveC4/CorpseComplex#19]
In version 1.0.6 of CorpseComplex I am unable to obtain the SoulBound enchantment despite the module being enabled.

#### Forge version:
forge-1.12.2-14.23.5.2768
#### Java version:
openjdk version "1.8.0_202"
#### OS version:
`$ uname -a`
`Linux Asunder 4.18.17_1 #1 SMP PREEMPT Tue Nov 6 19:10:50 UTC 2018 x86_64 GNU/Linux`
#### Current mods being used:
BetterThanMending-1.1.2.jar
BlueIceV1.0(1.12.2).jar
BowInfinityFix-1.12.2-rv5.1.jar
Clumps-3.1.2.jar
EnchantingTable-1.12-1.1.3.jar
FastFurnace-1.12.2-1.3.1.jar
FastWorkbench-1.12.2-1.7.2.jar
ForgivingVoid_1.12.2-1.0.23.jar
IncreaseMobs_1.12.2-v1.1.0.jar
PiTweaks-1.12-1.1.1.jar
coroutil-1.12.1-1.2.32.jar
corpsecomplex-1.12.2-1.0.6.jar
creaturebeacons-1.12.2-1.0.1.jar
diethopper-1.1.jar
enchcontrol-1.12.2-1.1.5-0.jar
jei_1.12.2-4.15.0.268.jar
respawntimer-1.12.2-2.0.0.0.jar
zombieawareness-1.12.1-1.11.16.jar
#
I have enabled the module, I have double and triple checked. The enchanted book does not show in JEI. I have also attempted to remove the enchcontrol mod but the effect remains the same.

I am not aware of most minecraft logging methods so if you could tell me which ones you want and where they are I would be happy to provide them

**Comment by TheIllusiveC4** [comment]
I believe I've encountered some issues with JEI before not showing the available enchantments correctly.

Can you try:
1) Enable the Soulbound enchantment module
2) Set the rarity to COMMON
3) Go into Creative and repeatedly enchant an item until Soulbound appears. I'd say try around 20 times and see if it appears in any of those iterations.

Basically this is just testing to see if, regardless of what JEI says, if you are able to get the enchantment to appear during enchanting.

**Comment by TheIllusiveC4** [comment]
Oh right, also, make sure the Inventory module is also enabled. It's a prerequisite for the Enchantment module since it's the parent module.
