### ISSUE TITLE
[suggestion] binding enchantment

### ISSUE THREAD

**Issue by Efimero** [TheIllusiveC4/CorpseComplex#2]
would you be so kind as to (optionally) add an enchanment to this mod that can be applied to items with regular enchantment/anvil+book mechanics that makes that item stay in the player's inventory regardless of the other mod settings? it would be great to have so the player can keep the items they consider important even if the setting is to drop/destroy them
maybe make the enchantment not applicable to items in the cursed list

thank youuuu <3 <3 <3

**Comment by TheIllusiveC4** [comment]
Interesting idea. I recall that, in previous versions of Minecraft, EnderIO had a similar enchantment called Soulbound. I'm not sure if anything has filled this niche in 1.12 yet. I'm very new to modding so I would have to look into how to code enchantments first, but I will see what I can do.

**Comment by TheIllusiveC4** [comment]
This task turned out easier than I expected since I had already laid out a lot of the groundwork necessary for this feature. I'll commit this to the next build once I finish bug testing.

**Comment by Efimero** [comment]
\o/ cheers <3
