### ISSUE TITLE
Suggestion: Different options depending on type of death

### ISSUE THREAD

**Issue by katubug** [TheIllusiveC4/CorpseComplex#21]
What I'd really like is the ability to set inventory damage (and maybe other things) etc based on whether the player was killed, drowned, starved etc. Like, a player who drowned may spawn with the anti-eating debuff. Someone killed by a monster would mostly take equipment damage (and maybe have some items looted by the enemy). Falling damage could damage inventory items, boots/leggings, and grant slowness for a while - and so on.

I haven't gotten to try the mod yet, but the wiki didn't seem to mention these features, so I thought I'd suggest them.

I understand if that's outside of your scope, but I figured I'd ask!

Thank so much for your time.

**Comment by TheIllusiveC4** [comment]
This is something I'm very interested in implementing, but Corpse Complex was my first mod so its systems weren't designed with this kind of advanced feature in mind. This will likely be a feature I can only implement in 1.14+ versions when I rewrite the mod from scratch.

**Comment by katubug** [comment]
Understandable! Thank you very much for the response, and I hope your rewrite goes well! :)

**Comment by TheIllusiveC4** [comment]
Implemented in MC 1.14.4+.
