### ISSUE TITLE
Problem with CC and Forge Essentials

### ISSUE THREAD

**Issue by llazzllo** [TheIllusiveC4/CorpseComplex#22]
I installed Forge Essentials and decided to remove it. I deleted the mod, and the folder it created(I didn't find a config), but I can't get Corpse Complex to work the way I had it set up. I've replaced the config for corpse complex, tried restarting the server without it and then again with it added back in, and nothing has worked. Forge Essentials changed something that did not change back once it was removed.

I posted on Forge Essentials Github first, but I thought I'd ask you too, just in case.

**Comment by TheIllusiveC4** [comment]
Was Corpse Complex working correctly before you removed Forge Essentials?
Does Corpse Complex work if you start up a new world instead of using your current world?

**Comment by llazzllo** [comment]
It was. We were using CC, Corpse, and GraveStone Mod together. It was working nicely. You kept the items we setup to keep, looted your corpse for the rest, and there was a gravestone left behind to let you know someone died there.  

I got it working again after Forge Essentials came out, but only by removing GraveStone.  Otherwise, you wouldn't keep anything at all.

**Comment by TheIllusiveC4** [comment]
Does Corpse Complex work if you start up a new world (in single player) instead of using your current world?
