### ISSUE TITLE
Setting to give player item(s) on respawn

### ISSUE THREAD

**Issue by Healz4Life** [TheIllusiveC4/CorpseComplex#25]
While using Hardcore Darkness along with Optifine I found it quite nice to be able to have night vision on respawn but soon realized it would be nicer to just have a torch, as it kinda hurts the game aesthetic to just be able to see everything at night, or have night vision in the day.

I'd think you can use the same code that gives you a death scroll and such, and then add the preferred method of, similar to the inventory settings, choose where said respawn items should go, such as offhand or armor slot.

Optionally it might be nice to remove these items from the player's inventory if they recover their items from a corpse or gravestone. Simplest way probably being to let the player choose an item that when right clicked or destroyed gets rid of just the respawn items.

**Comment by TheIllusiveC4** [comment]
I'll add in a pretty basic respawn items config option, which should satisfy the majority of use-cases. Including granularity on the level of the inventory settings involves a lot of complexity, so I'll save advanced functionality for this feature for future versions of Corpse Complex.
