### ISSUE TITLE
tech guns items seem to be deleted from existence if Inventory module is turned on

### ISSUE THREAD

**Issue by IronworksProductions** [TheIllusiveC4/CorpseComplex#27]
Something I have noticed is that techguns items seem to vanish from existence if you have the inventory module on. I have it so your hotbar and hands are kept, but if you have a gun and ammo in your hot bar they vanish from existence after death. They don't even end up in the corail tombstone.

**Comment by TheIllusiveC4** [comment]
Can you reproduce this issue with only Tech Guns and Corpse Complex installed?

**Comment by Sereath** [comment]
It literally took me a couple of years to find out why Techguns items would sometimes vanish after dying. The chance for it to happen is very random so it's hard to replicate...

:c
