### ISSUE TITLE
[request] rename soulbound to avoid confusion

### ISSUE THREAD

**Issue by Divineaspect** [TheIllusiveC4/CorpseComplex#3]
At least two other mods EnderIO and Ars Magica have soulbound enchantments which are absolute.
Could this enchantment be renamed Soulbinding or somesuch to avoid confusion?

**Comment by TheIllusiveC4** [comment]
I did consider this briefly as I was developing the feature, but I couldn't really think of a name I was happy with. I still can't, but Soulbinding seems good enough and I do want to avoid confusion. I'll put this out into the next build, which should be the release build.
