### ISSUE TITLE
[Feature Request] Per-Player Keep Inventory

### ISSUE THREAD

**Issue by SureinDragon** [TheIllusiveC4/CorpseComplex#35]
I've been looking high and low for a mod that lets me turn the Keep Inventory game rule off for most players, but able to put in a list of player names that allows those specific players to keep their whole inventory upon death. 

I play with a lot of people ranging from very experienced to very little experience, and these less experienced players tend to die often in the modpacks we play. I'd love to be able to ease their experience so they can relax and build/explore peacefully while the hardcore players can die to their hearts content. (I really do have friends that prefer to lose their stuff on death.)

I felt like this might be the best mod to put that kind of suggestion forward! But I totally understand if its something that cant be done. I primarily use the 1.12.2 version and would love the update for it, but I also understand it is falling out of date and is not always maintained.

**Comment by TheIllusiveC4** [comment]
Unfortunately this feature won't be coming to the 1.12.2 version. Maintenance status aside, the 1.12.2 version just doesn't have the infrastructure to make this possible. However, I will definitely add this to the 1.14.4+ versions, which were rewritten precisely to make features like this possible.

**Comment by SureinDragon** [comment]
This would be amazing! Thank you so much for the chance to make this request.
