### ISSUE TITLE
Pam's harvestcraft support

### ISSUE THREAD

**Issue by knoxhack** [TheIllusiveC4/CorpseComplex#5]
When I try to add a Pam's harvestcraft item as a curative item doesn't work. i have tried juices, smoothies.

**Comment by TheIllusiveC4** [comment]
I've successfully replicated this bug and will begin working on a solution. Are you on 1.12 or 1.10?

**Comment by TheIllusiveC4** [comment]
Assuming you're on 1.12, I've just pushed out a new version, 1.0.1.1. This should fix the problem with the curative items. If it doesn't, let me know so I can reopen this issue.

**Comment by knoxhack** [comment]
Awesome thank you, and yeah I'm in 1.12.2
