### ISSUE TITLE
1.15.2 Curios Crash

### ISSUE THREAD

**Issue by Her02N0one** [TheIllusiveC4/CorpseComplex#50]
#### Mods
Corpse Complex
Botania
Curios API (Forge)
Patchouli

#### Versions:
* Corpse Complex: 1.15.2-2.0-beta11
* Forge: 1.15.2 (31.2.45)
* Botania: r1.15-388
* Patchouli: 1.15.2-1.2-35
* Curios API: 1.15.2-2.0.2.6
#### Observed Behavior: 
Game crashes when you die with Botania curios in any curio slot.
(this may affect any curios, but I only have Botania)
#### Expected Behavior:
The game should not crash, and instead, let the player respawn
#### Steps to Reproduce:
1. set inventory keep chance to something greater than 0 in the server config
2. place a Botania curio in its curio slot
3. cause yourself to die. Easiest way would be "/kill"

Crash Log: https://hastebin.com/soxiyiwoto.properties

**Comment by TheIllusiveC4** [comment]
Fixed on Curios's end.
