### ISSUE TITLE
No Return Scroll option

### ISSUE THREAD

**Issue by Gonhog** [TheIllusiveC4/CorpseComplex#51]
#### Versions (Be specific, do not write "latest"):
* Corpse Complex: 1.16.3 - 4.0.0.2
* Forge: 1.16.3 - 34.1.33
#### Steps to Reproduce: Have Corpse Complex mod installed. 
1.
2.
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment]
This isn't a bug, the feature was removed after 1.12 and may or may not be re-implemented at a later date. As a feature request, see https://github.com/TheIllusiveC4/CorpseComplex/issues/44
