### ISSUE TITLE
Soulbinding

### ISSUE THREAD

**Issue by SheedRanko** [TheIllusiveC4/CorpseComplex#54]
Soulbinding is not not showing in JEI and I cannot seem to get it during playthrough, double checked the config to enable it &
to enable on books, both true

**Comment by TheIllusiveC4** [comment]
Please follow the bug report template. I need version numbers and reproduction steps. Also, please share your config file.

**Comment by SheedRanko** [comment]
sorry, new to this whole github thing
version: 1.12.2-1.0.11.1
config:
[corpsecomplex.txt](https://github.com/TheIllusiveC4/CorpseComplex/files/5793481/corpsecomplex.txt)

**Comment by TheIllusiveC4** [comment]
You have the Soulbinding enchantment module enabled, but you have the Inventory module itself disabled still. Since Soulbinding is a sub-module of Inventory, you need the Inventory module enabled as well if you want to use it.
