### ISSUE TITLE
Compatibility with Toolbelt

### ISSUE THREAD

**Issue by mahjerion** [TheIllusiveC4/CorpseComplex#55]
**Please describe the new feature or change.**
Basically, at the moment the toolbelt from https://www.curseforge.com/minecraft/mc-mods/tool-belt isn't kept on death when kept in a curios slot.
here's a crosspost from my issue tracker: https://github.com/mahjerion/Craft-to-Exile-Dissonance/issues/221

**Please describe why you want this feature.**
Similar to how you add configuration for curios and cosmetic armor, could you add it for toolbelt?

I actually don't know if this is a bug or feature request :|

**Comment by TheIllusiveC4** [comment]
You mention the Curios slot, but the tracker explicitly mentions it not being in the Curios slot. Which is accurate?

**Comment by mahjerion** [comment]
Hm, I'll double check.

EDIT my bad i even misread it somehow. yes in the toolbelt slot NOT curios

**Comment by democat3457** [comment]
any chance we could also get toolbelt compat for 1.12?

**Comment by TheIllusiveC4** [comment]
There is already Tool Belt compatibility on 1.12 (config option: Keep Toolbelt).

**Comment by democat3457** [comment]
well like for durability loss

**Comment by TheIllusiveC4** [comment]
Unfortunately, 1.12 will not receive any additional features.

Also, this compatibility does not have durability loss even in the later versions. Does the tool belt have durability? Or are you talking about the items inside it? Universally, nested items do not suffer any durability loss from Corpse Complex configurations.

**Comment by democat3457** [comment]
I meant the items inside it, but I guess it doesn't really matter now.
