### ISSUE TITLE
No config file?

### ISSUE THREAD

**Issue by sldains** [TheIllusiveC4/CorpseComplex#59]
So I'm using 1.16.5 and installed this mod through curseforge and even tried downloading it directly, but I can't get the config file to show up at all. Am I doing something wrong? It worked fine when I was running it on 1.12.

**Comment by TheIllusiveC4** [comment]
Did you look in your world save's `serverconfig` folder?

**Comment by sldains** [comment]
Ah, I was expecting it to be in the config folder like in 1.12. The wiki instructions really are only helpful for navigating the 1.12 version because the 1.16 version in the world save was much more confusing to figure out what to modify. I also didn't get the soulboud enchantments showing up in my enchantment list which is why I'd worried it wasn't working.

**Comment by TheIllusiveC4** [comment]
I _think_ it might not be showing up in the list because of a small bug that I just realized, but it should still work fine and show up in-game normally. Anyways, yeah, the wiki instructions haven't been updated to 1.14-1.16 content yet. I'm working on addressing that.
