### ISSUE TITLE
Unsure if I set this up correctly

### ISSUE THREAD

**Issue by DigitalSketch** [TheIllusiveC4/CorpseComplex#6]
Was looking for an alternative to the SoulBound enchant from EnderIO for 1.12, and found your mod!  I think I setup the config properly, but don't see any books or possible enchants with the SoulBind enchant on them.   I set the "Enable Inventory Module" to true, and then the "Enable Soulbinding Enchantment"to true... but don't see the enchant.  Am I missing something? Or does it just not show in JEI?

**Comment by TheIllusiveC4** [comment]
I just tested this on 1.12.2 with version 1.0.1.1 and the Soulbinding enchanted book shows up correctly for me in both JEI and the vanilla creative tab.

You have the process correct, if the values are all default then all you should have to do is set "Enable Inventory Module" to true and "Enable Soulbinding Enchantment" to true.

Did you change the configuration options through the in-game GUI? If so, did you make sure you restarted Minecraft after changing those values? And does this problem persist if you have only Corpse Complex installed? I also want to make sure you're searching for "Soulbinding" and not "Soulbound", as per what EnderIO called it.

If you have done that, then I'll need some more information. Can you give me:

Minecraft version
Forge version
Corpse Complex version
Inventory and soulbinding module configuration options
Are you on single player or testing this on a server?

**Comment by DigitalSketch** [comment]
I did make some other changes to the config, so I deleted it to reset it and set those two values to true.  I did this straight from the cfg, and not in game.  Still didn't see it.  I created a new profile with just CorpseComplex and JEI installed and it worked there, so I have a feeling it may be colliding with one of the other multiple mods I have installed on the other profile.  

I'm using the 1.0.1.1 version of CorpseComplex, Minecraft 1.12.2, Forge 14.23.0.2537 for both profiles.  

I'm not sure of any good way to list all the mods installed.  I did pastebin the log file from the last run here: https://pastebin.com/itWUedZV

Hope that helps.

**Comment by TheIllusiveC4** [comment]
If it's true that it works with just Corpse Complex and JEI installed, then I agree that perhaps it's a compatibility issue with another mod. There's little that I can do from my end without isolating the exact issue first. I'll try and parse through the log file, but it'll take a while since I don't even know what I'm looking for.

If you can provide your modlist, that would be helpful. I'm unaware of any easy way to do this, so worse case scenario you would have to list them all manually. If this is too much of an inconvenience, I recommend that you delete mods from your list in batches (or start from scratch and reinsert them in batches) until you find which one is causing the issue. I apologize that I cannot do more for you at this juncture, but I'll try my best to help in any way I can.

**Comment by DigitalSketch** [comment]
PowerShell is my friend :)  This is the current list of mods https://pastebin.com/fJeyrMWs  I'll see if I can copy a chunk of some of the mods into the test profile,  test it, remove them, copy more, etc and see if I can narrow it down.

**Comment by TheIllusiveC4** [comment]
Thank you very much. I'll do some investigating also and see if I can figure out the problem.

**Comment by DigitalSketch** [comment]
OK found out a few things.  It seems to conflict with any other mod that adds enchanted books.  This is what I did:
Copied a few mods that I know add enchanted books.  Did #soul in JEI to search for the book (that worked when it's just the CorpseComplex mod installed with JEI).  Looked at the creative tab with "soul" to find it, then hit "U" over a diamond sword to see if it showed up in the Anvil enchants, and this is what I got:

**CorpseComplex** alone: all that worked

**AdvancedRocketry**: Searching JEI it showed the "Airtight Seal" enchanted book, and with the anvil, it didn't show that the enchant was available.

**BiblioCraft**:: JEI showed "Eternal Compass" enchanted book, with the anvil, the enchant wasn't available

**DraconicEvolution**: Showed just "Enchanted Book" with no enchants on it in JEI, and in the anvil, it DID show SoulBinding as an enchant... so that was different.

**SoulShards**: Everything worked just like the CorpseComplex alone.

Not sure if that helps, but that's what I got from my testing.

**Comment by TheIllusiveC4** [comment]
That certainly helps a lot, thank you. I'll look into these conflicts and update you once I figure out what's going on.

**Comment by DigitalSketch** [comment]
Another small update, hitting "U" over the book, looks like it will enchant on armor, but nothing else.  :)   Really like the concept of this mod, so hoping this helps!

**Comment by TheIllusiveC4** [comment]
I've tested the mods that you mentioned in conjunction with Corpse Complex to see how the enchantments worked. My primary thought is that this is actually a problem with JEI not listing enchantments properly. Although my exact results were different from yours, I could see that sometimes enchantments were listed correctly or incorrectly depending on the exact list of mods present.

The main point I want to mention is that none of this actually impacted the gameplay from my testing. In all cases, I could still find the proper "Soulbinding" enchantment book in the creative tab. Similarly, after using the enchantment table multiple times, I found that I was able to enchant "Soulbinding" onto items as normal, even for items in which JEI did not list the enchanted book.

So, I think you can safely ignore whether or not JEI shows it or not. If you want to be sure, I recommend that you enable the enchantment in the config options, set "Rarity" to "Common", and then go into creative mode, set up an enchanting table with the maximum number of bookshelves, and just try to enchant a bunch of items to see if it actually shows up.

**Comment by DigitalSketch** [comment]
I'll do that thanks!

**Comment by TheIllusiveC4** [comment]
If there are no problems, I'll go ahead and close this issue.
