### ISSUE TITLE
No config file in config folder

### ISSUE THREAD

**Issue by AzureMonument** [TheIllusiveC4/CorpseComplex#61]
#### Versions (Be specific, do not write "latest"):
* Corpse Complex: 4.0.23
* Forge: 36.0.22
#### Steps to Reproduce: 
1. Download mod
2. Run minecraft
3. Check config folder

So I've recently thrown together a modpack with high difficulty, and added this mod to make things a little less punishing among all the death, however there is no configuration file, nor is there any key under 'controls' to let me edit the settings. (I've got controlling, and nothing pops up for corpse complex even when searching 'corpse' and other related labels.)

**Comment by TheIllusiveC4** [comment]
The configuration file is in your world save's `serverconfig` folder.
