### ISSUE TITLE
Config example?

### ISSUE THREAD

**Issue by FastBoye127** [TheIllusiveC4/CorpseComplex#62]
The config gives the following format info for this entry, but I've tried several permutations, including the one below, and keep getting crashes, apparently I'm not formatting it properly.

#List of items to always keep, drop, or destroy, regardless of other settings
	#Format: modid:item;[keep/drop/destroy]
	itemSettings = []
	
"  itemSettings = antiqueatlas:antique_atlas [keep]   " seems like the proper way to do it, but doesn't work.
	
Could you provide an example of how this should be properly formatted?

**Comment by TheIllusiveC4** [comment]
```
itemSettings = ["antiqueatlas:antique_atlas;keep"]
```

**Comment by FastBoye127** [comment]
This worked! Thank you!
