### ISSUE TITLE
[1.12.2] Item Loss when combined with The Betweelands Blessing effect

### ISSUE THREAD

**Issue by SeriousCreeper** [TheIllusiveC4/CorpseComplex#69]
#### Versions (Be specific, do not write "latest"):
* Corpse Complex: corpsecomplex-1.12.2-1.0.12.0.jar
* Forge: 2847
#### Observed Behavior:
The Betweenlands has a block called "Simulacrum" that does a variety of things. One of them being the "Blessing" effect which give the player some extra health should they die. 
However if using Corpse Complex and enabling the inventory module as well as Keep Hotbar (as an example), once the player "dies" and gets health back by the simulacrum, the items in the hotbar get deleted. 

Here is a video demonstrating it: https://streamable.com/ifmhnz
#### Expected Behavior:
Items in hotbar to not get deleted.
#### Steps to Reproduce:
1. Install Betweenlands and Corpse Complex
2. Enable Inventory Module and one of the Keep Modules (in my case Hotbar)
3. In creative mode, place the Simulacrum, and shift+right click it until the effect says "Blessing" 
4. Place an Offering Table in front of it and add a spirit fruit
5. Wait for a few seconds for the Blessed effect to apply to your player
6. Put something into your hotbar (if thats the module you enabled), and die

**Comment by TheIllusiveC4** [comment]
Unfortunately, I no longer support 1.12.2.

**Comment by SeriousCreeper** [comment]
Ah sorry i didn't know, thanks though!
