### ISSUE TITLE
[1.12.2-1.0.12.0] Experience module broken

### ISSUE THREAD

**Issue by goldeneggbabby** [TheIllusiveC4/CorpseComplex#70]
<html>
<body>
No other mods used.

#### Version:
* Corpse Complex: corpsecomplex-1.12.2-1.0.12.0.jar
* Forge: Forge 14.23.5.2855

#### Observed Behavior:
With experience module configured properly, experience after death is RESET to values PRIOR to spending any xp. For example, if a player has 50 levels, then spends 30 and dies, their experience will be RESET to the original 50, which it will then remove a % of based on the config. It is a game breaking bug, as one could easily farm limitless enchantments or any use of experience points.

#### Expected Behavior:
Experience shouldn't reset to an old initial value, it should take into account spending XP by any means before death.
#### Steps to Reproduce:
1. Open config file for corpsecomplex.cfg, enable experience module, set "Keep All XP" to false, set "Lost XP Percent" to 0.17 (or something else partial), "Maximum Recoverable XP" to 0, and "Recoverable XP Percent" to 0.4 (or something else partial).
2. Create single player world with cheats on, use command to add significant XP such as "/xp 4000 @a"
3. Using a give command, create an enchanting table or anvil to spend experience in a significant amount
4. Use "/summon zombie" several times to have these mobs kill you
5. Respawn and see that your experience has reset to a far greater amount than the amount you had when you died.
</body>
</html>

**Comment by TheIllusiveC4** [comment]
This is probably related to https://github.com/TheIllusiveC4/CorpseComplex/issues/56
I suspect that the values for the experience aren't kept in sync by Minecraft, so some assumptions made by Corpse Complex about experience calculations are incorrect and causing some erroneous values to be used.
This should be fixed in 1.16.5, but unfortunately I am no longer making 1.12.2 updates.
