### ISSUE TITLE
Compatibility Crash with EpicFight Mod

### ISSUE THREAD

**Issue by Malloks** [TheIllusiveC4/CorpseComplex#71]
#### Versions (Be specific, do not write "latest"):
* Corpse Complex:1.16.5-7.1.2.409
* Forge:36.2.2
#### Steps to Reproduce:
1. Die (I used /kill but it doesn't matter)
2.
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).
No crash log, when the game crashes it freezes forever if force closed the crash log is just "unexpected crash"

**Comment by TheIllusiveC4** [comment]
This isn't the mod you think it is. The Corpse mod is a different mod.

**Comment by Malloks** [comment]
I'm so sorry, I don't know how I messed up the mod
