### ISSUE TITLE
Game crashes whenever I try to keep specific items on death. Please see log.

### ISSUE THREAD

**Issue by JetpackRescue** [TheIllusiveC4/CorpseComplex#74]
1.16.5- 4.0.2.6

Your mod crashes the game on world load if I change anything in the itemoverrides.toml in the defaultconfigs folder. I'm trying to keep specific items no matter what on death. This is what the config looks like

```[[itemOverrides]]
  dropDurabilityLoss = 1.0
  keepDurabilityLoss = 1.0
  items = ["cgm:assault_rifle;keep"]```

That causes the world to not load, and crash instead.

Is that the right format?

is this the right format for multiple items?
`items = ["cgm:assault_rifle;keep", "cgm:basic_bullet;keep", "minecraft:stick"]`

??? The configs are not explained well, I suggest you redo them with an example of the format.


in the server config, if I set it to this:

```	#List of items to always keep, drop, or destroy, regardless of other settings
	#Format: modid:item;[keep/drop/destroy]
	itemSettings = ["cgm:assault_rifle;keep"]```

So if I add anything to item settings, or to items, the game crashes. It doesn't crash if they're just empty brackets.
the game crashes on world load, here's as much of a crash report as it gives me.

https://pastebin.com/v2Vc6JsA

**Comment by TheIllusiveC4** [comment]
>   dropDurabilityLoss = 1.0
>   keepDurabilityLoss = 1.0
>   items = ["cgm:assault_rifle;keep"]

You can't add `keep` or anything else to the `items` list in the `corpsecomplex-itemoverrides.toml` file. It's just the name, nothing else. If you want to just always keep the item, you can use the `itemSettings` field in the `corpsecomplex-server.toml` file instead.

> #List of items to always keep, drop, or destroy, regardless of other settings
> 	#Format: modid:item;[keep/drop/destroy]
> 	itemSettings = ["cgm:assault_rifle;keep"]

This should be correct. Your crash report is only for the first problem above, I'd need to see a crash report for specifically this issue to see what's going on if this doesn't work on your end.

> The configs are not explained well, I suggest you redo them with an example of the format.

The `corpsecomplex-server.toml` fields are all commented with examples of the format. I apologize that the other two configuration files do not have documentation yet, I'll get to that eventually. Until then, you can continue getting support from me directly either here or on Discord.
