### ISSUE TITLE
I don't have any config files for corpse complex and was wondering if its the version or a bug

### ISSUE THREAD

**Issue by darthracion** [TheIllusiveC4/CorpseComplex#79]
#### Versions (Be specific, do not write "latest"):
* Corpse Complex: 4.0.2.8
* Forge: 36.2.34 or 1.16.5
#### Steps to Reproduce:
1.
2.
3.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

**Comment by TheIllusiveC4** [comment]
The configuration files for Corpse Complex on 1.16.5 are located in your world save's `serverconfig` folder.
